export enum ErrorCode {
  STATUS_NOT_FOUND = "STATUS_NOT_FOUND",
  CANNOT_VOTE_FOR_OLD_MEMES = "CANNOT_VOTE_FOR_OLD_MEMES",
  CANNOT_VOTE_FOR_OWN_MEME = "CANNOT_VOTE_FOR_OWN_MEME",
  YOU_ALREADY_LIKED_THIS_STATUS = "YOU_ALREADY_LIKED_THIS_STATUS",
  CANNOT_DISLIKE_A_MEME = "CANNOT_DISLIKE_A_MEME",
  STATUS_HAVE_NOT_BEEN_LIKED = "STATUS_HAVE_NOT_BEEN_LIKED",
  CANNOT_CREATE_MEME_WITHOUT_ATTACHMENTS = "CANNOT_CREATE_MEME_WITHOUT_ATTACHMENTS",
  BALANCE_IS_NOT_ENOUGH_TO_VOTE = "BALANCE_IS_NOT_ENOUGH_TO_VOTE"
}
