export enum ErrorCode {
  STATUS_NOT_FOUND = "STATUS_NOT_FOUND",
  CANNOT_VOTE_FOR_OLD_MEMES = "CANNOT_VOTE_FOR_OLD_MEMES",
  CANNOT_VOTE_FOR_OWN_MEME = "CANNOT_VOTE_FOR_OWN_MEME",
  YOU_ALREADY_LIKED_THIS_STATUS = "YOU_ALREADY_LIKED_THIS_STATUS",
}
